// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBghu6w1FRUDvJ_FU3BF1Gy2uDgl4fYthg',
    appId: '1:998024258455:web:5d47e26a9ef70543eb1ad2',
    messagingSenderId: '998024258455',
    projectId: 'adidas-app-1f7a2',
    authDomain: 'adidas-app-1f7a2.firebaseapp.com',
    storageBucket: 'adidas-app-1f7a2.appspot.com',
    measurementId: 'G-572WL4GNH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBq_3OQ3GuliCAK8HBSs_576kkqqm1lAY',
    appId: '1:998024258455:android:d95e757737c4ab2beb1ad2',
    messagingSenderId: '998024258455',
    projectId: 'adidas-app-1f7a2',
    storageBucket: 'adidas-app-1f7a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8aOU80ZnaH029O1CtalKjag3KUHhA4oU',
    appId: '1:998024258455:ios:6de6a34c609e8161eb1ad2',
    messagingSenderId: '998024258455',
    projectId: 'adidas-app-1f7a2',
    storageBucket: 'adidas-app-1f7a2.appspot.com',
    iosClientId: '998024258455-4phvc1spdncseumd354c6njd6ma077gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.adidasApp',
  );
}
